server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: department_route
          uri: lb://department-service
          predicates:
            - Path=/department/**
        - id: employee_route
          uri: lb://employee-service
          predicates:
            - Path=/home/employee/**
